name: AntiAbuseCommands
version: 1.0
main: net.enderbyteprograms.antiabuse.AntiAbuseMain
description: Prevent abuse when using vanilla commands
api-version: 1.21.4
author: Enderbyte09
softdepend: [Multiverse-Core,BooksWithoutBorders,SimpleTPA,WorldEdit]
commands:
  aac:
    description: Anti Abuse Commands
permissions:
  aac.give.exempt:
    default: op
  aac.teleport.exempt:
    default: op
  aac.gamemode.exempt:
    default: op
  aac.multiverse.exempt:
    default: op
  aac.transfer.exempt:
    default: op
  aac.summon.exempt:
    default: op
  aac.settitle.exempt:
    default: op
  aac.setlore.exempt:
    default: op
  aac.parkour.exempt:
    default: op
  aac.enchant.exempt:
    default: op
  aac.attribute.exempt:
    default: op
  aac.worldedit.exempt:
    default: op
  aac.tpa.exempt:
    default: op
  aac.exempt:
    default: op
    children:
      aac.give.exempt: true
      aac.gamemode.exempt: true
      aac.multiverse.exempt: true
      aac.transfer.exempt: true
      aac.teleport.exempt: true
      aac.summon.exempt: true
      aac.settitle.exempt: true
      aac.setlore.exempt: true
      aac.parkour.exempt: true
      aac.tpa.exempt: true
      aac.enchant.exempt: true
      aac.attribute.exempt: true
      aac.worldedit.exempt: true
  aac.admin:
    default: op
    children:
      aac.exempt: true